version: 1.0.{build}
build: off
build: false
services:
  - postgresql101

environment:
  PGUSER: "postgres"
  PGPASSWORD: "Password12!"
  PGPORT: 5432
  PGHOST: "localhost"


init:
  - "set PATH=C:\\Program Files\\PostgreSQL\\10\\bin\\;%PATH%"
  - "psql -c \"SELECT VERSION()\""
  