version: 1.0.{build}
build: off



environment:
  PGUSER: "postgres"
  PGPASSWORD: "Password12!"
  PGPORT: 5432
  PGHOST: "localhost"

  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

services:
  - postgresql101

init:
  - "set PATH=C:\\Program Files\\PostgreSQL\\10\\bin\\;%PATH%"

build_script:
  - "psql -c \"SELECT VERSION()\""
  - "createdb relational_data_loader"


test_script:
  - "test_full_refresh_from_csv.cmd"
  - "test_incremental_refresh_from_csv.cmd"