version: 1.0.{build}
build: off



environment:
  PGUSER: "postgres"
  PGPASSWORD: "Password12!"
  PGPORT: 5432
  PGHOST: "localhost"

services:
  - postgresql94

init:
  - "set PATH=C:\\Program Files\\PostgreSQL\\10\\bin\\;%PATH%"
  - "psql -c \"SELECT VERSION()\""
